(function() {
  var list = new List()
  list.storeNote("toastie")
  list.storeNote("cats")
  list.storeNote("turtles")
  var view = new View(list)
  var controller = new NoteController(list)
  var htmlList = view.htmlListOutput()
  controller.getHTMLList(htmlList)
})()
